### PR TITLE
Fetch all values which match the pattern into the header AUT-2218

### PR DESCRIPTION
**Pull request by aswirski-cloudentity**

### CODE REVIEW

**Comment by holowinski** [comment]
Is this a breaking change compared to the previous behaviour ?

**Review by holowinski — APPROVED** [review]

**Comment by jdabrowski** [comment]
please add jira ticket to PR title so that others can understand why and what is being done :)

**Comment by ppodbielski-cloudentity** [comment]
is this 1.5.0 content?

**Comment by aswirski-cloudentity** [comment]
created identical pr towards release/1.5.0, already merged

**Pull request closed without merging**
